// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: UI_Setting

#include "../ui.h"

void ui_ScreenSettingMain_screen_init(void)
{
ui_ScreenSettingMain = lv_obj_create(NULL);
lv_obj_set_style_bg_color(ui_ScreenSettingMain, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenSettingMain, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelSettingMainContainer = lv_obj_create(ui_ScreenSettingMain);
lv_obj_set_width( ui_PanelSettingMainContainer, 720);
lv_obj_set_height( ui_PanelSettingMainContainer, 498);
lv_obj_set_x( ui_PanelSettingMainContainer, 150 );
lv_obj_set_y( ui_PanelSettingMainContainer, 98 );
lv_obj_set_flex_flow(ui_PanelSettingMainContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanelSettingMainContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanelSettingMainContainer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_PanelSettingMainContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelSettingMainContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelSettingMainContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelSettingMainContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

/* ── 1. WiFi ── */
ui_PanelSettingMainContainerItem1 = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_height( ui_PanelSettingMainContainerItem1, 70);
lv_obj_set_width( ui_PanelSettingMainContainerItem1, lv_pct(100));
lv_obj_set_y( ui_PanelSettingMainContainerItem1, -230 );
lv_obj_set_align( ui_PanelSettingMainContainerItem1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSettingMainContainerItem1, LV_OBJ_FLAG_SCROLLABLE );
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelSettingMainContainerItem1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelSettingMainContainerItem1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem1, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem1, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ImagePanelSettingMainContainer1WiFi = lv_img_create(ui_PanelSettingMainContainerItem1);
lv_img_set_src(ui_ImagePanelSettingMainContainer1WiFi, &ui_img_wifi_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer1WiFi, LV_SIZE_CONTENT);
lv_obj_set_height( ui_ImagePanelSettingMainContainer1WiFi, LV_SIZE_CONTENT);
lv_obj_set_y( ui_ImagePanelSettingMainContainer1WiFi, 0 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer1WiFi, 20 );
lv_obj_set_align( ui_ImagePanelSettingMainContainer1WiFi, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer1WiFi, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer1WiFi, LV_OBJ_FLAG_SCROLLABLE );

ui_ImagePanelSettingMainContainer1Arrow = lv_img_create(ui_PanelSettingMainContainerItem1);
lv_img_set_src(ui_ImagePanelSettingMainContainer1Arrow, &ui_img_arrow_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer1Arrow, LV_SIZE_CONTENT);
lv_obj_set_height( ui_ImagePanelSettingMainContainer1Arrow, LV_SIZE_CONTENT);
lv_obj_set_y( ui_ImagePanelSettingMainContainer1Arrow, 0 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer1Arrow, -20 );
lv_obj_set_align( ui_ImagePanelSettingMainContainer1Arrow, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer1Arrow, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer1Arrow, LV_OBJ_FLAG_SCROLLABLE );

ui_LabelPanelSettingMainContainer1WiFi = lv_label_create(ui_PanelSettingMainContainerItem1);
lv_obj_set_width( ui_LabelPanelSettingMainContainer1WiFi, LV_SIZE_CONTENT);
lv_obj_set_height( ui_LabelPanelSettingMainContainer1WiFi, LV_SIZE_CONTENT);
lv_obj_set_x( ui_LabelPanelSettingMainContainer1WiFi, 90 );
lv_obj_set_y( ui_LabelPanelSettingMainContainer1WiFi, 0 );
lv_obj_set_align( ui_LabelPanelSettingMainContainer1WiFi, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LabelPanelSettingMainContainer1WiFi,"Wi-Fi");
lv_obj_set_style_text_font(ui_LabelPanelSettingMainContainer1WiFi, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

/* ── 2. Volume (Audio) ── */
ui_PanelSettingMainContainerItem3 = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_width( ui_PanelSettingMainContainerItem3, lv_pct(100));
lv_obj_set_height( ui_PanelSettingMainContainerItem3, 70);
lv_obj_set_y( ui_PanelSettingMainContainerItem3, -150 );
lv_obj_set_align( ui_PanelSettingMainContainerItem3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSettingMainContainerItem3, LV_OBJ_FLAG_SCROLLABLE );
lv_obj_set_style_border_color(ui_PanelSettingMainContainerItem3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelSettingMainContainerItem3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem3, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem3, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ImagePanelSettingMainContainer3Volume = lv_img_create(ui_PanelSettingMainContainerItem3);
lv_img_set_src(ui_ImagePanelSettingMainContainer3Volume, &ui_img_sound_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer3Volume, LV_SIZE_CONTENT);
lv_obj_set_height( ui_ImagePanelSettingMainContainer3Volume, LV_SIZE_CONTENT);
lv_obj_set_y( ui_ImagePanelSettingMainContainer3Volume, 0 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer3Volume, 20 );
lv_obj_set_align( ui_ImagePanelSettingMainContainer3Volume, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer3Volume, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer3Volume, LV_OBJ_FLAG_SCROLLABLE );

ui_ImagePanelSettingMainContainer3Arrow = lv_img_create(ui_PanelSettingMainContainerItem3);
lv_img_set_src(ui_ImagePanelSettingMainContainer3Arrow, &ui_img_arrow_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer3Arrow, LV_SIZE_CONTENT);
lv_obj_set_height( ui_ImagePanelSettingMainContainer3Arrow, LV_SIZE_CONTENT);
lv_obj_set_y( ui_ImagePanelSettingMainContainer3Arrow, 0 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer3Arrow, -20 );
lv_obj_set_align( ui_ImagePanelSettingMainContainer3Arrow, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer3Arrow, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer3Arrow, LV_OBJ_FLAG_SCROLLABLE );

ui_LabelPanelSettingMainContainer3Volume = lv_label_create(ui_PanelSettingMainContainerItem3);
lv_obj_set_width( ui_LabelPanelSettingMainContainer3Volume, LV_SIZE_CONTENT);
lv_obj_set_height( ui_LabelPanelSettingMainContainer3Volume, LV_SIZE_CONTENT);
lv_obj_set_x( ui_LabelPanelSettingMainContainer3Volume, 90 );
lv_obj_set_y( ui_LabelPanelSettingMainContainer3Volume, 0 );
lv_obj_set_align( ui_LabelPanelSettingMainContainer3Volume, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LabelPanelSettingMainContainer3Volume,"Volume");
lv_obj_set_style_text_font(ui_LabelPanelSettingMainContainer3Volume, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

/* ── 3. Brightness (Display) ── */
ui_PanelSettingMainContainerItem4 = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_width( ui_PanelSettingMainContainerItem4, lv_pct(100));
lv_obj_set_height( ui_PanelSettingMainContainerItem4, 70);
lv_obj_set_y( ui_PanelSettingMainContainerItem4, -70 );
lv_obj_set_align( ui_PanelSettingMainContainerItem4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSettingMainContainerItem4, LV_OBJ_FLAG_SCROLLABLE );
lv_obj_set_style_border_color(ui_PanelSettingMainContainerItem4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelSettingMainContainerItem4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem4, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem4, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ImagePanelSettingMainContainer4Light = lv_img_create(ui_PanelSettingMainContainerItem4);
lv_img_set_src(ui_ImagePanelSettingMainContainer4Light, &ui_img_light_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer4Light, LV_SIZE_CONTENT);
lv_obj_set_height( ui_ImagePanelSettingMainContainer4Light, LV_SIZE_CONTENT);
lv_obj_set_y( ui_ImagePanelSettingMainContainer4Light, 0 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer4Light, 20 );
lv_obj_set_align( ui_ImagePanelSettingMainContainer4Light, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer4Light, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer4Light, LV_OBJ_FLAG_SCROLLABLE );

ui_ImagePanelSettingMainContainer4Arrow = lv_img_create(ui_PanelSettingMainContainerItem4);
lv_img_set_src(ui_ImagePanelSettingMainContainer4Arrow, &ui_img_arrow_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer4Arrow, LV_SIZE_CONTENT);
lv_obj_set_height( ui_ImagePanelSettingMainContainer4Arrow, LV_SIZE_CONTENT);
lv_obj_set_y( ui_ImagePanelSettingMainContainer4Arrow, 0 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer4Arrow, -20 );
lv_obj_set_align( ui_ImagePanelSettingMainContainer4Arrow, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer4Arrow, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer4Arrow, LV_OBJ_FLAG_SCROLLABLE );

ui_LabelPanelSettingMainContainer4Light = lv_label_create(ui_PanelSettingMainContainerItem4);
lv_obj_set_width( ui_LabelPanelSettingMainContainer4Light, LV_SIZE_CONTENT);
lv_obj_set_height( ui_LabelPanelSettingMainContainer4Light, LV_SIZE_CONTENT);
lv_obj_set_x( ui_LabelPanelSettingMainContainer4Light, 90 );
lv_obj_set_y( ui_LabelPanelSettingMainContainer4Light, 0 );
lv_obj_set_align( ui_LabelPanelSettingMainContainer4Light, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LabelPanelSettingMainContainer4Light,"Brightness");
lv_obj_set_style_text_font(ui_LabelPanelSettingMainContainer4Light, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

/* ── 4. Ethernet ── */
ui_ethernetMainItem = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_width( ui_ethernetMainItem, lv_pct(100));
lv_obj_set_height( ui_ethernetMainItem, 70);
lv_obj_set_y( ui_ethernetMainItem, 10 );
lv_obj_set_align( ui_ethernetMainItem, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ethernetMainItem, LV_OBJ_FLAG_SCROLLABLE );
lv_obj_set_style_border_color(ui_ethernetMainItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ethernetMainItem, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ethernetMainItem, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_ethernetMainItem, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ethernetMainIcon = lv_img_create(ui_ethernetMainItem);
lv_img_set_src(ui_ethernetMainIcon, &app_ethernet_icon);
lv_obj_set_width( ui_ethernetMainIcon, LV_SIZE_CONTENT);
lv_obj_set_height( ui_ethernetMainIcon, LV_SIZE_CONTENT);
lv_obj_set_y( ui_ethernetMainIcon, 0 );
lv_obj_set_x( ui_ethernetMainIcon, 20 );
lv_obj_set_align( ui_ethernetMainIcon, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ethernetMainIcon, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_clear_flag( ui_ethernetMainIcon, LV_OBJ_FLAG_SCROLLABLE );

ui_ethernetMainArrow = lv_img_create(ui_ethernetMainItem);
lv_img_set_src(ui_ethernetMainArrow, &ui_img_arrow_png);
lv_obj_set_width( ui_ethernetMainArrow, LV_SIZE_CONTENT);
lv_obj_set_height( ui_ethernetMainArrow, LV_SIZE_CONTENT);
lv_obj_set_y( ui_ethernetMainArrow, 0 );
lv_obj_set_x( ui_ethernetMainArrow, -20 );
lv_obj_set_align( ui_ethernetMainArrow, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_ethernetMainArrow, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_clear_flag( ui_ethernetMainArrow, LV_OBJ_FLAG_SCROLLABLE );

ui_ethernetMainLable = lv_label_create(ui_ethernetMainItem);
lv_obj_set_width( ui_ethernetMainLable, LV_SIZE_CONTENT);
lv_obj_set_height( ui_ethernetMainLable, LV_SIZE_CONTENT);
lv_obj_set_x( ui_ethernetMainLable, 90 );
lv_obj_set_y( ui_ethernetMainLable, 0 );
lv_obj_set_align( ui_ethernetMainLable, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_ethernetMainLable,"Ethernet");
lv_obj_set_style_text_font(ui_ethernetMainLable, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

/* ── 5. RS485 ── */
ui_rs485MainItem = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_width( ui_rs485MainItem, lv_pct(100));
lv_obj_set_height( ui_rs485MainItem, 70);
lv_obj_set_y( ui_rs485MainItem, 90 );
lv_obj_set_align( ui_rs485MainItem, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_rs485MainItem, LV_OBJ_FLAG_SCROLLABLE );
lv_obj_set_style_border_color(ui_rs485MainItem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_rs485MainItem, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rs485MainItem, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_rs485MainItem, 255, LV_PART_MAIN| LV_STATE_PRESSED);

LV_IMG_DECLARE(ui_img_rs485_png);

lv_obj_t *rs485_img = lv_img_create(ui_rs485MainItem);
lv_img_set_src(rs485_img, &ui_img_rs485_png);
lv_obj_set_width( rs485_img, LV_SIZE_CONTENT);
lv_obj_set_height( rs485_img, LV_SIZE_CONTENT);
lv_obj_set_y( rs485_img, 0 );
lv_obj_set_x( rs485_img, 20 );
lv_obj_set_align( rs485_img, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( rs485_img, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_clear_flag( rs485_img, LV_OBJ_FLAG_SCROLLABLE );

ui_rs485MainArrow = lv_img_create(ui_rs485MainItem);
lv_img_set_src(ui_rs485MainArrow, &ui_img_arrow_png);
lv_obj_set_width( ui_rs485MainArrow, LV_SIZE_CONTENT);
lv_obj_set_height( ui_rs485MainArrow, LV_SIZE_CONTENT);
lv_obj_set_y( ui_rs485MainArrow, 0 );
lv_obj_set_x( ui_rs485MainArrow, -20 );
lv_obj_set_align( ui_rs485MainArrow, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_rs485MainArrow, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_clear_flag( ui_rs485MainArrow, LV_OBJ_FLAG_SCROLLABLE );

ui_rs485MainLabel = lv_label_create(ui_rs485MainItem);
lv_obj_set_width( ui_rs485MainLabel, LV_SIZE_CONTENT);
lv_obj_set_height( ui_rs485MainLabel, LV_SIZE_CONTENT);
lv_obj_set_x( ui_rs485MainLabel, 90 );
lv_obj_set_y( ui_rs485MainLabel, 0 );
lv_obj_set_align( ui_rs485MainLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_rs485MainLabel,"RS485");
lv_obj_set_style_text_font(ui_rs485MainLabel, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

/* ── 6. About Device ── */
ui_PanelSettingMainContainerItem5 = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_width( ui_PanelSettingMainContainerItem5, lv_pct(100));
lv_obj_set_height( ui_PanelSettingMainContainerItem5, 70);
lv_obj_set_y( ui_PanelSettingMainContainerItem5, 170 );
lv_obj_set_align( ui_PanelSettingMainContainerItem5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSettingMainContainerItem5, LV_OBJ_FLAG_SCROLLABLE );
lv_obj_set_style_border_color(ui_PanelSettingMainContainerItem5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelSettingMainContainerItem5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem5, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem5, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ImagePanelSettingMainContainer5About = lv_img_create(ui_PanelSettingMainContainerItem5);
lv_img_set_src(ui_ImagePanelSettingMainContainer5About, &ui_img_about_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer5About, LV_SIZE_CONTENT);
lv_obj_set_height( ui_ImagePanelSettingMainContainer5About, LV_SIZE_CONTENT);
lv_obj_set_y( ui_ImagePanelSettingMainContainer5About, 0 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer5About, 20 );
lv_obj_set_align( ui_ImagePanelSettingMainContainer5About, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer5About, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer5About, LV_OBJ_FLAG_SCROLLABLE );

ui_ImagePanelSettingMainContainer5Arrow = lv_img_create(ui_PanelSettingMainContainerItem5);
lv_img_set_src(ui_ImagePanelSettingMainContainer5Arrow, &ui_img_arrow_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer5Arrow, LV_SIZE_CONTENT);
lv_obj_set_height( ui_ImagePanelSettingMainContainer5Arrow, LV_SIZE_CONTENT);
lv_obj_set_y( ui_ImagePanelSettingMainContainer5Arrow, 0 );
lv_obj_set_x( ui_ImagePanelSettingMainContainer5Arrow, -20 );
lv_obj_set_align( ui_ImagePanelSettingMainContainer5Arrow, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer5Arrow, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer5Arrow, LV_OBJ_FLAG_SCROLLABLE );

ui_LabelPanelSettingMainContainer5About = lv_label_create(ui_PanelSettingMainContainerItem5);
lv_obj_set_width( ui_LabelPanelSettingMainContainer5About, LV_SIZE_CONTENT);
lv_obj_set_height( ui_LabelPanelSettingMainContainer5About, LV_SIZE_CONTENT);
lv_obj_set_x( ui_LabelPanelSettingMainContainer5About, 90 );
lv_obj_set_y( ui_LabelPanelSettingMainContainer5About, 0 );
lv_obj_set_align( ui_LabelPanelSettingMainContainer5About, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LabelPanelSettingMainContainer5About,"About Device");
lv_obj_set_style_text_font(ui_LabelPanelSettingMainContainer5About, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_PanelSettingMainContainerItem1, ui_event_PanelSettingMainContainerItem1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PanelSettingMainContainerItem3, ui_event_PanelSettingMainContainerItem3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PanelSettingMainContainerItem4, ui_event_PanelSettingMainContainerItem4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ethernetMainItem, ui_event_PanelSettingMainContainerItemEthernet, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_rs485MainItem, ui_event_PanelSettingMainContainerItemRS485, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PanelSettingMainContainerItem5, ui_event_PanelSettingMainContainerItem5, LV_EVENT_ALL, NULL);

}
