// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: UI_Setting

#include "../ui.h"

void ui_ScreenSettingEthernet_screen_init(void)
{
    ui_ScreenSettingEthernet = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_ScreenSettingEthernet, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSettingEthernet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* ========== Top panel: icon + "Ethernet" + status + IP + switch ========== */
    ui_PanelEthernetSwitch = lv_obj_create(ui_ScreenSettingEthernet);
    lv_obj_set_width(ui_PanelEthernetSwitch, lv_pct(90));
    lv_obj_set_height(ui_PanelEthernetSwitch, 65);
    lv_obj_set_x(ui_PanelEthernetSwitch, 43);
    lv_obj_set_y(ui_PanelEthernetSwitch, 10);
    lv_obj_clear_flag(ui_PanelEthernetSwitch, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_PanelEthernetSwitch, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelEthernetSwitch, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PanelEthernetSwitch, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelEthernetSwitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageEthernetSwitch = lv_img_create(ui_PanelEthernetSwitch);
    lv_img_set_src(ui_ImageEthernetSwitch, &app_ethernet_icon);
    lv_obj_set_y(ui_ImageEthernetSwitch, 0);
    lv_obj_set_x(ui_ImageEthernetSwitch, lv_pct(1));
    lv_obj_set_align(ui_ImageEthernetSwitch, LV_ALIGN_LEFT_MID);

    ui_LabelEthernetSwitch = lv_label_create(ui_PanelEthernetSwitch);
    lv_obj_set_x(ui_LabelEthernetSwitch, lv_pct(10));
    lv_obj_set_align(ui_LabelEthernetSwitch, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelEthernetSwitch, "Ethernet");
    lv_obj_set_style_text_font(ui_LabelEthernetSwitch, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchEthernet = lv_switch_create(ui_PanelEthernetSwitch);
    lv_obj_set_width(ui_SwitchEthernet, 55);
    lv_obj_set_height(ui_SwitchEthernet, 28);
    lv_obj_set_y(ui_SwitchEthernet, 0);
    lv_obj_set_x(ui_SwitchEthernet, lv_pct(87));
    lv_obj_set_align(ui_SwitchEthernet, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_SwitchEthernet, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SwitchEthernet, lv_color_hex(0x4CAF50), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_radius(ui_SwitchEthernet, 14, LV_PART_MAIN | LV_STATE_DEFAULT);


    /* ========== Speed test area ========== */
    /* Wrapper for two side-by-side panels */
    lv_obj_t *ui_PanelEthernetSpeedWrapper = lv_obj_create(ui_ScreenSettingEthernet);
    lv_obj_set_width(ui_PanelEthernetSpeedWrapper, lv_pct(90));
    lv_obj_set_height(ui_PanelEthernetSpeedWrapper, 350);
    lv_obj_set_x(ui_PanelEthernetSpeedWrapper, 43);
    lv_obj_set_y(ui_PanelEthernetSpeedWrapper, 85);
    lv_obj_clear_flag(ui_PanelEthernetSpeedWrapper, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_PanelEthernetSpeedWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelEthernetSpeedWrapper, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* --- Left card: Ethernet Speed Test (UDP Server) --- */
    ui_PanelEthernetServer = lv_obj_create(ui_PanelEthernetSpeedWrapper);
    lv_obj_set_width(ui_PanelEthernetServer, lv_pct(47));
    lv_obj_set_height(ui_PanelEthernetServer, lv_pct(100));
    lv_obj_set_align(ui_PanelEthernetServer, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_PanelEthernetServer, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_PanelEthernetServer, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelEthernetServer, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PanelEthernetServer, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelEthernetServer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelEthernetServer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelEthernetServer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_PanelEthernetServer, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEthernetServerTitle = lv_label_create(ui_PanelEthernetServer);
    lv_label_set_text(ui_LabelEthernetServerTitle, "Ethernet Speed Test");
    lv_obj_set_style_text_font(ui_LabelEthernetServerTitle, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEthernetServerTitle, lv_color_hex(0x4CAF50), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEthernetServerIP = lv_label_create(ui_PanelEthernetServer);
    lv_obj_set_y(ui_LabelEthernetServerIP, 30);
    lv_label_set_text(ui_LabelEthernetServerIP, "IP: --");
    lv_obj_set_style_text_font(ui_LabelEthernetServerIP, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEthernetServerIP, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEthernetServerInfo = lv_label_create(ui_PanelEthernetServer);
    lv_obj_set_y(ui_LabelEthernetServerInfo, 55);
    lv_label_set_text(ui_LabelEthernetServerInfo, "UDP | Port: 5001");
    lv_obj_set_style_text_font(ui_LabelEthernetServerInfo, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEthernetServerInfo, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEthernetServerStatus = lv_label_create(ui_PanelEthernetServer);
    lv_obj_set_y(ui_LabelEthernetServerStatus, 75);
    lv_label_set_text(ui_LabelEthernetServerStatus, "Status: Idle");
    lv_obj_set_style_text_font(ui_LabelEthernetServerStatus, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEthernetServerStatus, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEthernetServerSpeed = lv_label_create(ui_PanelEthernetServer);
    lv_obj_set_y(ui_LabelEthernetServerSpeed, 105);
    lv_label_set_text(ui_LabelEthernetServerSpeed, "Peak: -- Mbps");
    lv_obj_set_style_text_font(ui_LabelEthernetServerSpeed, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEthernetServerSpeed, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelEthernetServerSpeed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonEthernetServerStart = lv_btn_create(ui_PanelEthernetServer);
    lv_obj_set_width(ui_ButtonEthernetServerStart, lv_pct(80));
    lv_obj_set_height(ui_ButtonEthernetServerStart, 42);
    lv_obj_set_y(ui_ButtonEthernetServerStart, 155);
    lv_obj_set_align(ui_ButtonEthernetServerStart, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_ButtonEthernetServerStart, 21, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonEthernetServerStart, lv_color_hex(0x4CAF50), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonEthernetServerStart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_ButtonEthernetServerStart, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_ButtonEthernetServerStart, LV_OBJ_FLAG_SCROLLABLE);

    ui_LabelEthernetServerButton = lv_label_create(ui_ButtonEthernetServerStart);
    lv_obj_set_align(ui_LabelEthernetServerButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEthernetServerButton, "Start Server");
    lv_obj_set_style_text_font(ui_LabelEthernetServerButton, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEthernetServerButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Warning label (hidden by default, shown when clicking start without eth connected)
    ui_LabelEthernetServerWarn = lv_label_create(ui_PanelEthernetServer);
    lv_obj_set_width(ui_LabelEthernetServerWarn, lv_pct(100));
    lv_obj_set_y(ui_LabelEthernetServerWarn, 185);
    lv_obj_set_style_text_font(ui_LabelEthernetServerWarn, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEthernetServerWarn, lv_color_hex(0xF44336), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelEthernetServerWarn, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_LabelEthernetServerWarn, LV_OBJ_FLAG_HIDDEN);

    // Command hint text
    ui_LabelEthernetServerCmd = lv_label_create(ui_PanelEthernetServer);
    lv_obj_set_width(ui_LabelEthernetServerCmd, lv_pct(100));
    lv_obj_set_y(ui_LabelEthernetServerCmd, 220);
    lv_label_set_text(ui_LabelEthernetServerCmd, "PC: iperf -u -c your ip -t 10 -i 2 -b 100M");
    lv_obj_set_style_text_font(ui_LabelEthernetServerCmd, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEthernetServerCmd, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelEthernetServerCmd, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* --- Right card: WiFi Speed Test --- */
    ui_PanelEthernetClient = lv_obj_create(ui_PanelEthernetSpeedWrapper);
    lv_obj_set_width(ui_PanelEthernetClient, lv_pct(47));
    lv_obj_set_height(ui_PanelEthernetClient, lv_pct(100));
    lv_obj_set_align(ui_PanelEthernetClient, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_PanelEthernetClient, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_PanelEthernetClient, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelEthernetClient, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PanelEthernetClient, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PanelEthernetClient, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelEthernetClient, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelEthernetClient, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_PanelEthernetClient, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEthernetClientTitle = lv_label_create(ui_PanelEthernetClient);
    lv_label_set_text(ui_LabelEthernetClientTitle, "WiFi Speed Test");
    lv_obj_set_style_text_font(ui_LabelEthernetClientTitle, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEthernetClientTitle, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEthernetClientIP = lv_label_create(ui_PanelEthernetClient);
    lv_obj_set_y(ui_LabelEthernetClientIP, 30);
    lv_label_set_text(ui_LabelEthernetClientIP, "IP: --");
    lv_obj_set_style_text_font(ui_LabelEthernetClientIP, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEthernetClientIP, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEthernetClientInfo = lv_label_create(ui_PanelEthernetClient);
    lv_obj_set_y(ui_LabelEthernetClientInfo, 55);
    lv_label_set_text(ui_LabelEthernetClientInfo, "TCP | Port: 5001");
    lv_obj_set_style_text_font(ui_LabelEthernetClientInfo, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEthernetClientInfo, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEthernetClientStatus = lv_label_create(ui_PanelEthernetClient);
    lv_obj_set_y(ui_LabelEthernetClientStatus, 75);
    lv_label_set_text(ui_LabelEthernetClientStatus, "Status: Idle");
    lv_obj_set_style_text_font(ui_LabelEthernetClientStatus, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEthernetClientStatus, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEthernetClientSpeed = lv_label_create(ui_PanelEthernetClient);
    lv_obj_set_y(ui_LabelEthernetClientSpeed, 105);
    lv_label_set_text(ui_LabelEthernetClientSpeed, "Peak: -- Mbps");
    lv_obj_set_style_text_font(ui_LabelEthernetClientSpeed, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEthernetClientSpeed, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelEthernetClientSpeed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonEthernetClientStart = lv_btn_create(ui_PanelEthernetClient);
    lv_obj_set_width(ui_ButtonEthernetClientStart, lv_pct(80));
    lv_obj_set_height(ui_ButtonEthernetClientStart, 42);
    lv_obj_set_y(ui_ButtonEthernetClientStart, 155);
    lv_obj_set_align(ui_ButtonEthernetClientStart, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_ButtonEthernetClientStart, 21, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonEthernetClientStart, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonEthernetClientStart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_ButtonEthernetClientStart, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_ButtonEthernetClientStart, LV_OBJ_FLAG_SCROLLABLE);

    ui_LabelEthernetClientButton = lv_label_create(ui_ButtonEthernetClientStart);
    lv_obj_set_align(ui_LabelEthernetClientButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelEthernetClientButton, "Start Test");
    lv_obj_set_style_text_font(ui_LabelEthernetClientButton, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEthernetClientButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Warning label
    ui_LabelEthernetClientWarn = lv_label_create(ui_PanelEthernetClient);
    lv_obj_set_width(ui_LabelEthernetClientWarn, lv_pct(100));
    lv_obj_set_y(ui_LabelEthernetClientWarn, 185);
    lv_obj_set_style_text_font(ui_LabelEthernetClientWarn, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEthernetClientWarn, lv_color_hex(0xF44336), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelEthernetClientWarn, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_LabelEthernetClientWarn, LV_OBJ_FLAG_HIDDEN);

    // Command hint text
    ui_LabelEthernetClientCmd = lv_label_create(ui_PanelEthernetClient);
    lv_obj_set_width(ui_LabelEthernetClientCmd, lv_pct(100));
    lv_obj_set_y(ui_LabelEthernetClientCmd, 220);
    lv_label_set_text(ui_LabelEthernetClientCmd, "PC: iperf -c your ip -t 10 -i 2");
    lv_obj_set_style_text_font(ui_LabelEthernetClientCmd, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelEthernetClientCmd, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelEthernetClientCmd, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

}
